### ISSUE TITLE
`send` no longer works after a `receive`

### ISSUE THREAD

**Issue by kenhkan** [noflo/noflo-test#3]
Is it intentional for `send` to no long work after a `receive.<anything>` has been called? I'm working on a caching component but can't test it because it throws the following error. Apparently it repeats the previous send/receive multiple times.

```
    ✗ another empty IPs is emitted 
      TypeError: Cannot read property 'port' of undefined 
      at buildTests (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/lib/test.coffee:109:34) 
      at Array.forEach (native) 
      at Object.buildTests (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/lib/test.coffee:105:26) 
      at runTest (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/node_modules/vows/lib/vows.js:132:26) 
      at EventEmitter.<anonymous> (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/node_modules/vows/lib/vows.js:78:9) 
      at EventEmitter.emit (events.js:126:20) 
      at EventEmitter.vows.describe.options.Emitter.emit (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/node_modules/vows/lib/vows.js:237:24) 
      at env.callback.that.emitter.ctx (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/node_modules/vows/lib/vows/context.js:32:52) 
      at process.startup.processNextTick.process._tickCallback (node.js:245:9)
    ✓ another empty IPs is emitted
    ✓ another empty IPs is emitted
    ✗ another empty IPs is emitted 
      TypeError: Cannot read property 'port' of undefined 
      at buildTests (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/lib/test.coffee:109:34) 
      at Array.forEach (native) 
      at Object.buildTests (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/lib/test.coffee:105:26) 
      at runTest (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/node_modules/vows/lib/vows.js:132:26) 
      at EventEmitter.<anonymous> (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/node_modules/vows/lib/vows.js:78:9) 
      at EventEmitter.emit (events.js:126:20) 
      at EventEmitter.vows.describe.options.Emitter.emit (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/node_modules/vows/lib/vows.js:237:24) 
      at env.callback.that.emitter.ctx (/Users/kenhkan/Desktop/hacking/noflo-/flow/node_modules/noflo-test/node_modules/vows/lib/vows/context.js:32:52) 
      at process.startup.processNextTick.process._tickCallback (node.js:245:9)
```

**Comment by bergie** [comment]
Well, we should really focus on https://github.com/flowbased/fbp-spec
